### ISSUE TITLE
"Apple Computer" needs to be changed to "Apple" in the xml dtd.

### ISSUE THREAD

**Issue by tomandersen** [bleything/plist#17]
But this is a small bug considering the whole thing fails if your values have any return characters in them.

**Comment by AknEp** [comment]
+1, may I PR?

**Comment by musl** [comment]
How about honoring the original DTD if present and using the Apple version if not?

Consider the case where you want to load a plist file, pass the data up a chain of observers, and you only want to replace the original file (and trigger other actions) only if the plist file actually changed. If parsing and then immediately dumping a plist file yields the same file, that case would be trivial.

Also, if folks are using this gem for non-apple plists (Does that even happen?) it'd be nice.

**Comment by danielgalasko** [comment]
+1

**Comment by patsplat** [comment]
Hi all,

Yes a PR would be appreciated. Please include tests.

FYI for those involved: this library was originally created to help me
export iPhoto libraries. @bleything got the project moved from sourceforge
to github and maintained it for some time.

Since then there have been many changes to the plist format including a
binary format etc. Pull requests for any of these features will be
appreciated.

Thank you for your use of the library.

Cheers,

Patrick

**Comment by danielgalasko** [comment]
Looks like this is actually done in https://github.com/bleything/plist/commit/81bba1b39e066710dba6a4b4098b5559ab38613e I think what we need is a version bump

**Comment by patsplat** [comment]
version bumped.  it doesn't really all that much, if you inspect your machine you'll see plenty of plists with both DTDs

**Comment by danielgalasko** [comment]
I don't see a version bump? The reason why this matters is that other dependencies that use this spec to update plists (Fastlane is one such) cause Xcode generated plists to be modified unnecessarily. After a commit action, a subsequent open with Xcode triggers the plist to be modified again. You can read more about this issue here https://github.com/fastlane/fastlane/pull/1180

**Comment by danielgalasko** [comment]
So once the version is bumped and the gem spec updated I can go ahead and update Fastlane's spec to use the latest version:)
